### ISSUE TITLE
Mistake in code

### ISSUE THREAD

**Issue by M-N-S-15** [irsol/udacity-bertelsmann-data-science-challenge-scholarship-2018#1]
https://github.com/irsol/udacity-bertelsmann-data-science-challenge-scholarship-2018/blob/71b620e60132ae04af339f044b214111640efe83/basic_sql_lesson28/quizzes.sql#L108

the question asked for the companies that start with C so it should be 
WHERE name LIKE 'C%';  
but they wrote "WHERE name LIKE '%C%';"

**Comment by irsol** [comment]
@MNS-15 thanks!
